In [6]:
import math
import sympy as smp
import numpy as np
from sympy import *

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [7]:
[ x, xdot ] = symbols('x xdot')
l, m = symbols('l m',real=True)
xddot = 0.3*x + 0.6*xdot/(x**4.1)
xddot = 0.3*x + 0.6*xdot #/(x**4.1)
integrand = xddot*(x**l)*(xdot**(m-1))
simp = powsimp(expand(integrand))
nterm = len(simp.args)
print(integrand)
print(simp.args)

x**l*xdot**(m - 1)*(0.3*x + 0.6*xdot)
(0.3*x**(l + 1)*xdot**(m - 1), 0.6*x**l*xdot**m)


In [8]:
equation_string = '0.3*u + 0.6*udot'
u, udot = smp.symbols('u udot')
l, m = smp.symbols('l m',real=True)
equation = smp.parse_expr( equation_string )
integrand = equation*(u**l)*(udot**(m-1))
simp = smp.powsimp(smp.expand(integrand))
nterm = len(simp.args)
print(equation)
print(simp.args)
print('[{:s}]'.format(', '.join( [str(a) for a in simp.args])))

0.3*u + 0.6*udot
(0.3*u**(l + 1)*udot**(m - 1), 0.6*u**l*udot**m)
[0.3*u**(l + 1)*udot**(m - 1), 0.6*u**l*udot**m]


In [9]:
num_int_coords = 2

if num_int_coords == 2:
    [ x, xdot ] = symbols('x xdot')
    l, m = symbols('l m',real=True)
    xddot = 0.3*x + 0.6*xdot/(x**4.1)
    integrand = xddot*(x**l)*(xdot**(m-1))
elif num_int_coords == 1:
    x = symbols('x')
    l = symbols('l',real=True)
    xdot = 4*x - 2*x**2
    integrand = xdot*(x**(l-1))

terms = powsimp(expand(integrand)).args
nterm = len(terms)
if num_int_coords > 1:
    real_nterm = nterm + 1
else:
    real_nterm = nterm

exp  = zeros(real_nterm,num_int_coords)
coef = zeros(real_nterm,1)

#terms = zeros(nterm)
for i in range(nterm):
    #terms[i] = simp.args[i]

    exp[i,0] = terms[i].as_coeff_exponent(x)[1]
    if num_int_coords > 1:
        exp[ i,1]  = terms[i].as_coeff_exponent(xdot)[1]
        coef[i,0] = m*poly(terms[i]).coeffs()[0]
    elif num_int_coords == 1:
        coef[i,0] = l*poly(terms[i]).coeffs()[0]
    
if num_int_coords > 1:
    exp[ nterm,0] = l - 1
    exp[ nterm,1] = m + 1
    coef[nterm,0] = l
    
exp
coef

Matrix([
[  l + 1, m - 1],
[l - 4.1,     m],
[  l - 1, m + 1]])

Matrix([
[0.3*m],
[0.6*m],
[    l]])

In [10]:
print('[{:s}]'.format(', '.join( [str(a) for a in exp])))

[l + 1, m - 1, l - 4.1, m, l - 1, m + 1]


In [11]:
# SHB: This was old stuff, putting here just in case

num_int_coords = 2
num_max_terms = 3
def transportterms(x,xdot,xddot,num_max_terms,num_int_coords):
    # l -> c0
    # m -> c1
    # (n if it exists -> c2)
    c0, c1 = symbols('c0 c1')
    exp  = zeros(num_max_terms,num_int_coords)
    coef = zeros(num_max_terms,1)
    exp[0,0] = c0-1  #[ c0-1, c1 + 1 ]
    exp[0,1] = c1 + 1
    coef[0] = c0
    # if xddot = x + xdot
    # then integrand -> (x+xdot)*x^l xdot^m-1
    #                -> (x^l+1 + xdot*x^l)*(x*xdot^m-1 + xdot^m)
    #                -> (x^{l+1}*xdot^{m} + x^{l}*xdot^{m}) P d{x} d{xdo}
    #                -> [l+1,m] + [l,m]
    # these are all multiplied by m out front, so
    exp[1,0] = c0+1
    exp[1,1] = c1
    exp[2,0] = c0
    exp[2,1] = c1
    coef[1,0] = c1
    coef[2,0] = c1
    return exp,coef

In [21]:
print(exp, coef)

Matrix([[l + 1, m - 1], [l - 4.1, m], [l - 1, m + 1]]) Matrix([[0.3*m], [0.6*m], [l]])


In [12]:
X = [smp.symbols('X%d' % x) for x in range(3)]
I = [smp.symbols('i%d' % i) for i in range(3)]

integrand = X[0]**I[0]
for x in range(1,3):
    for i in range(1,3):
        integrand *= (X[x]**I[i])
print(integrand)

X0**i0*X1**i1*X1**i2*X2**i1*X2**i2


In [13]:
X[0] = smp.symbols('y')


In [14]:
[smp.symbols('0') for x in range(3)]

[0, 0, 0]

In [15]:
T = np.zeros(3)
T = np.array([0.0,1.0,1.0,0.0])

XYZ = np.zeros([5,4,3])
XYZ[1] = np.array([[0.1,0.2,0.3],[0.4,0.5,0.6],[0.7,0.8,0.9],[0.1,0.2,0.3]])
XYZ[2] = np.array([[0.2,0.3,0.4],[0.5,0.6,0.7],[1.0,0.9,1.0],[1.1,1.2,1.3]])
XYZ[3] = np.array([[0.3,0.4,0.5],[1.5,1.6,1.7],[1.4,1.0,1.1],[0.2,0.3,0.4]])
XYZ[4] = np.array([[0.4,0.5,0.6],[2.5,2.6,2.7],[2.0,1.0,1.2],[0.4,0.5,0.6]])
print(XYZ)

[[[0.  0.  0. ]
  [0.  0.  0. ]
  [0.  0.  0. ]
  [0.  0.  0. ]]

 [[0.1 0.2 0.3]
  [0.4 0.5 0.6]
  [0.7 0.8 0.9]
  [0.1 0.2 0.3]]

 [[0.2 0.3 0.4]
  [0.5 0.6 0.7]
  [1.  0.9 1. ]
  [1.1 1.2 1.3]]

 [[0.3 0.4 0.5]
  [1.5 1.6 1.7]
  [1.4 1.  1.1]
  [0.2 0.3 0.4]]

 [[0.4 0.5 0.6]
  [2.5 2.6 2.7]
  [2.  1.  1.2]
  [0.4 0.5 0.6]]]


In [16]:
T = np.where( T < 1.0e-9, 1.0e-9, T )
i = ( T > 0.5 ).nonzero()[0]

x_ref = 0.7

XYZ_in = XYZ[:,i]
print(XYZ_in.shape)
x_p = XYZ_in[:,:,0]
print(x_p)

(5, 2, 3)
[[0.  0. ]
 [0.4 0.7]
 [0.5 1. ]
 [1.5 1.4]
 [2.5 2. ]]


In [17]:
x_ref = 1.2
x_min = x_p.min(axis = 0)
x_max = x_p.max(axis = 0)

xx = ( x_p - x_ref ) * ( x_p - x_ref )
print(xx)
i_ref = xx.argmin(axis=0)
print (i_ref)

print( x_p[:,0])
x_p[3,0] > x_ref
i_left = i_ref - 1 

[[1.44 1.44]
 [0.64 0.25]
 [0.49 0.04]
 [0.09 0.04]
 [1.69 0.64]]
[3 2]
[0.  0.4 0.5 1.5 2.5]


np.True_

In [18]:
201*21

4221

In [19]:
eta_min = 0.005
eta_max = 0.1

y_ref = -0.0083245
H_ref = 0.02

y_min = y_ref + H_ref * eta_min 
y_max = y_ref + H_ref * eta_max
y_mid = 0.5 * ( y_max + y_min )
L_y   = y_max - y_min

print (L_y)
print(y_min, y_mid, y_max)
print(y_mid - 0.5*L_y)

0.0019000000000000006
-0.008224500000000001 -0.007274500000000001 -0.0063245
-0.008224500000000001
